---
# ansible/roles/common_ssh/handlers/main.yml

- name: Restart ssh
  ansible.builtin.service:
    name: "{{ common_ssh_service_name }}"
    state: restarted
  when: common_ssh_restart_service | bool
