---
# Node-specific patch for talos-cp-3
machine:
  network:
    interfaces:
      - interface: ens18
        addresses:
          - 10.40.0.43/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.40.0.1
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: talos-cp-3
auto: off
